---
title: "Gamete Abundance Analysis"
author: "hputnam"
date: "2024-04-01"
output: html_document
---

This script will analyze gamete abundance over time. 
## Load packages 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("tidyverse")
library("gridExtra")
```

## Load data & select specific columns 
```{r}
Abundance <- read.csv("data/histology_data.csv", header = T, na.strings = c("", "NA"))

### Format data from wide to long 
Abundance_long <- pivot_longer(Abundance, cols = starts_with("Stage"), names_to = "Stage", values_to = "Value")

df_relative_abundance <- Abundance_long %>%
  group_by(colony_id,replicate_id, site, sex, month, Stage) %>%
  summarise(tots = sum(Value)) %>%
  group_by(colony_id, replicate_id, site, sex, month) %>%
  mutate(grand.tots = sum(tots)) %>%
  mutate(freq = tots/grand.tots) 

#df_relative_abundance <- replace(df_relative_abundance, is.na(df_relative_abundance), 0)

df_relative_abundance$month <- factor(df_relative_abundance$month, levels = c("January","February", "March","April", "May","June", "July", "August", "September","October",  "November"))

df_relative_abundance$group <- paste0(df_relative_abundance$month,"_", df_relative_abundance$colony_id)

df_relative_abundance$month <- factor(df_relative_abundance$month, levels = c("January","February", "March","April", "May","June", "July", "August", "September","October",  "November"))

#df_relative_abundance$Stage <- factor(df_relative_abundance$Stage, levels = c("StageI","StageII","StageIII","StageIV"))

my_tag <- c("", "", "", "", "", "", "", "", "", "", "",
            "No Data", "", "", "", "", "", "", "", "", "", "")

anno <- data.frame(x1 = 0.3,  y1 = 3, lab = "No Data")
anno


```

Male Gametes
```{r}
male_df_relative_abundance <- df_relative_abundance %>%
  filter(!sex=="female")

Male <- male_df_relative_abundance %>% ggplot(aes(x=replicate_id, y=freq, group=Stage, color=Stage, fill=Stage)) +
  geom_col()+
  facet_wrap(c("site", "month"), ncol=11)+
  facet_nested("site" * site ~ "month" * month)+
  theme_bw()+
  ylab("Proportion of Sperm")+
  theme(strip.text.x = element_text(size = 8, colour = "black"),axis.text.x=element_blank(), legend.position = "top", axis.title.x=element_blank())
Male
# Male <-  tag_facet(Male, x = -Inf, y = -Inf, 
#           vjust = -1, hjust = -0.25,
#           open = "", close = "",
#           fontface = 1,
#           size = 3,
#           family = "serif",
#           tag_pool = my_tag)
# 
# Male
```

Female Gametes
```{r}
female_df_relative_abundance <- df_relative_abundance %>%
  filter(!sex=="male")


Female <- female_df_relative_abundance %>% ggplot(aes(x=replicate_id, y=freq, group=Stage, color=Stage, fill=Stage, label=site)) +
  geom_col()+
  #facet_wrap(c("site", "month"), ncol=11)+
  facet_nested("site" * site ~ "month" * month)+
  theme_bw()+
  ylab("Proportion of Eggs")+
  theme(strip.text.x = element_text(size = 8, colour = "black"),axis.text.x = element_text(angle = 90), legend.position = "none", axis.title.x=element_blank())
Female

# Female <- tag_facet(Female, x = -Inf, y = -Inf, 
#           vjust = -1, hjust = -0.25,
#           open = "", close = "",
#           fontface = 1,
#           size = 3,
#           family = "serif",
#           tag_pool = my_tag)
# Female
```
Arrange and save plots
```{r}

plots <- grid.arrange(Male, Female, nrow = 2)

#https://stackoverflow.com/questions/36941197/overall-label-for-facets

ggsave("output/Gametogenesis.pdf", plots , width = 10, height = 6)
ggsave("output/Gametogenesis.jpg", plots , width = 10, height = 6)


```
