---
title: "biomass.Rmd"
author: "HM Putnam, AS Huffmyer"
date: "10/26/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

## install packages if you dont already have them
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("plotrix")) install.packages("plotrix")

# load packages
library(tidyverse)
library(plotrix)
library(gridExtra)

```

```{r }
#Read in biomass data
Data <- read.csv("../data/biomass_data.csv")
#Data <- na.omit(Data)

#Load tissue homogenate volume
homog_vol <- read.csv("../data/homogenate_vols.csv", header=TRUE)

# Load Surface area data
sa <- read_csv("../output/surface.area.calc.csv")

# Coral sample metadata
metadata <- read_csv("data/corals_sampled.csv")

# Join homogenate volumes and surface area with sample metadata
Data <- metadata %>% left_join(homog_vol %>% select(full_sample_id,homog_vol_ml)) %>%
  left_join(sa %>% select(full_sample_id,surface.area.cm2)) %>%
  left_join(Data, by="full_sample_id")

#Standardize DW for initial pan weight
Data <- Data %>%
  mutate(DW.corr.g = dry.pan.mass.g - initial.mass.g)

#Standardize DW for volume input
Data <- Data %>%
  mutate(DW.corr.vol.g = (DW.corr.g/volume)*homog_vol_ml) %>%
  mutate(DW.mg.cm2 = (DW.corr.vol.g*1000) / surface.area.cm2)

#Standardize Ash for initial pan weight
Data <- Data %>%
  mutate(Ash.corr.g = burnt.pan.mass.g - initial.mass.g)

#Standardize Ash for volume input
Data <- Data %>%
  mutate(Ash.corr.vol.g = (Ash.corr.g/volume)*homog_vol_ml) %>%
  mutate(Ash.mg.cm2 = (Ash.corr.vol.g*1000) / surface.area.cm2)

#Calculate AFDW
Data <- Data %>%
  mutate(AFDW.mg.cm2 = DW.mg.cm2 - Ash.mg.cm2)


```


```{r}
#summarize Dry Biomass mean and sem 

monthorder <- c("January", "February","March", "April","May",
                "June",  "July", "August", "September", 
                "October","November")

Data$timepoint <- factor(Data$timepoint,levels=monthorder)
Data$group <- paste0(Data$timepoint, "_", Data$site)

Data<-Data[!is.na(Data$partner),]#remove rows that are not identified for species and site

write.csv(Data, "/Users/hputnam/Desktop/junk.csv")
 
# Plot 
DW <- Data %>%
  ggplot(aes(x = timepoint, y = DW.mg.cm2, group=group, color=site)) +
  geom_boxplot(aes(group=group, color=site))+
  geom_jitter(width = 0.1) + # Plot all points
  scale_color_manual(values=c("#E69F00", "#56B4E9")) +
  #stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1),    # Plot standard error
  #             geom = "errorbar", color = c("black"), width = 0.5) +
  #stat_summary(fun.y = mean, geom = "point", color = "black")+           # Plot mean
  labs(x = "", y = "Biomass (mg/cm2)") +
  facet_wrap("partner")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

DW

AFDW <- Data %>%
  ggplot(aes(x = timepoint, y = AFDW.mg.cm2, group=group, color=site)) +
  geom_boxplot(aes(group=group, color=site))+
  geom_jitter(width = 0.1) + # Plot all points
  scale_color_manual(values=c("#E69F00", "#56B4E9")) +
  #stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1),    # Plot standard error
  #             geom = "errorbar", color = c("black"), width = 0.5) +
  #stat_summary(fun.y = mean, geom = "point", color = "black")+           # Plot mean
  labs(x = "", y = "AFDW Biomass (mg/cm2)") +
  facet_wrap("partner")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

AFDW 

biomass.plots <- grid.arrange(DW, AFDW, nrow = 2)

ggsave("output/Biomass.pdf", biomass.plots , width = 8, height = 6)
ggsave("output/Biomass.jpg", biomass.plots , width = 8, height = 6)

```


 
