---
title: "Protein analysis"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

## install packages if you dont already have them
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("broom")) install.packages("broom")

# load packages
library(tidyverse)
library(broom)
```

# Import data
```{r}
# List protein data files
prot_path = "data/protein/host/"                                              # Path to prot data directory
all_prot_files <- list.files(path = prot_path, pattern = "*.csv")          # List all files in directory
prot_platemaps <- list.files(path = prot_path, pattern = "platemap")       # List platemap files
prot_data_files <- setdiff(all_prot_files, prot_platemaps)                 # List data files

# Read in all files into tibble
df <- tibble(file = prot_data_files) %>%
  separate(file, into = c("date", "plate", "partner"), remove = FALSE) %>%
  unite(plate, date, plate, partner) %>%
  mutate(platemap = map(plate, ~read_csv(paste0(prot_path, ., "_BCA_platemap.csv"))),
         prot_data = map(file, ~read_csv(paste0(prot_path, .)) %>% rename(well = Well)))

# Merge platemap and data for each plate
df <- df %>%
  mutate(merged = map2(platemap, prot_data, ~ right_join(.x, .y)))
```

# Plot standard curve
```{r}
# Create standard curve following kit instructions
standards <- tribble(
  ~std, ~BSA_ug.mL,
  "A",        2000,
  "B",        1500,
  "C",        1000,
  "D",         750,
  "E",         500,
  "F",         250,
  "G",         125,
  "H",          25,
  "I",           0
)

std_curve <- df %>%
  unnest(merged) %>%
  filter(grepl("Standard", full_sample_id)) %>%
  select(plate, well, full_sample_id, abs562 = `562:562`) %>%
  rename(std = full_sample_id) %>%
  mutate(std = str_sub(std, 9, 9)) %>%
  #group_by(std) %>%
  #summarise(abs562 = mean(abs562)) %>%                       # calculate mean of standard duplicates
  #mutate(abs562.adj = abs562 - abs562[std == "I"]) %>%       # subtract blank absorbace value from all
  left_join(standards)


## Fit linear model for standard curve
# mod <- lm(BSA_ug.mL ~ abs562, data = std_curve)
# coef(mod)

## Fit nonlinear model for standard curve
#mod <- nls(formula = BSA_ug.mL ~ z + a * exp(b * abs562), start = list(z = 0, a = 1, b = 1), data = std_curve)
#fitted <- mod %>% broom::augment()

mod <- lm <- lm(BSA_ug.mL ~ abs562, data = std_curve)

fitted <- mod %>% broom::augment()

# Plot standard curve
std_curve_plot <- std_curve %>%
  ggplot(aes(x = abs562, y = BSA_ug.mL)) +
  geom_point(color = "red", size = 3) 

std_curve_plot + 
  geom_line(data = fitted, aes(x = abs562, y = .fitted)) +
  labs(title = "Standard curve")
```

# Calculate protein concentrations
```{r}
# Calculate protein concentration for all samples using standard curve
prot <- df %>%
  unnest(merged) %>%
  filter(!grepl("Standard", full_sample_id)) %>%                     # Get just samples (not standards)
  select(plate, well, full_sample_id, abs562 = `562:562`) %>%        # Select only needed columns
  filter(!is.na(full_sample_id)) %>%                                 # Filter out empty wells
  filter(full_sample_id != "BK") %>%                                 # Filter out blank wells
  mutate(prot_ug.mL = map_dbl(abs562, ~ predict(mod, newdata = data.frame(abs562 = .))))    # Use standard curve to convert absorbance to protein

std_curve_plot + 
  geom_point(data = prot, aes(x = abs562, y = prot_ug.mL), pch = "X", cex = 5, alpha = 0.3) +
  labs(title = "All samples projected on standard curve")

prot <- prot %>%
  group_by(full_sample_id) %>%
  summarise(n = n(), prot_ug.mL = mean(abs562))

```

# Normalize to surface area
```{r}
# Surface area data
sa <- read.csv("output/surface.area.calc.csv")
# Tissue homogenate volume data
homog_vols <- read_csv("data/homogenate_vols.csv") 

# Coral sample metadata
metadata <- read_csv("data/corals_sampled.csv") 

# Join homogenate volumes and surface area with sample metadata
metadata <- left_join(metadata, homog_vols, by="full_sample_id") %>%
  left_join(sa, by="full_sample_id")

# Join prot data with metadata
prot <- left_join(prot, metadata, by="full_sample_id") %>%
  mutate(prot_ug = prot_ug.mL * homog_vol_ml,
         prot_ug.cm2 = prot_ug / surface.area.cm2,
         prot_mg.cm2 = prot_ug.cm2 / 1000)
```

# Plot results by species and site
```{r}
monthorder <- c("January", "February","March", "April","May",
                "June",  "July", "August", "September", 
                "October","November")

prot$timepoint.x <- factor(prot$timepoint.x,levels=monthorder)
prot$group <- paste0(prot$timepoint.x, "_", prot$site.x)

# Plot 
prot %>%
  ggplot(aes(x = timepoint.x, y = prot_mg.cm2, group=group, color=site.x)) +
  geom_boxplot(aes(group=group, color=site.x))+
  geom_jitter(width = 0.1) + # Plot all points
  scale_color_manual(values=c("#E69F00", "#56B4E9")) +
  #stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1),    # Plot standard error
  #             geom = "errorbar", color = c("black"), width = 0.5) +
  #stat_summary(fun.y = mean, geom = "point", color = "black")+           # Plot mean
  labs(x = "", y = "Host Soluble Protein (mg/cm2)") +
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

# Write data to output file
```{r}
# Write protein data to output file
prot %>%
  select(full_sample_id, prot_ug, prot_ug.cm2) %>%
  mutate(partner="host")%>%
  write_csv(., path = "output/host_protein.csv")
```

