---
title: "Symbiont density analysis"
output: html_document
---

#Author: HM Putnam 
#Edited by: HM Putnam


```{r setup, include = FALSE}
## install packages if you dont already have them
if (!require("tidyverse")) install.packages("tidyverse")

# load packages
library(tidyverse)
```

# Import data
```{r}
# Cell count data
sym_counts <- read_csv("data/sym_counts_data.csv")

# Surface area data
sa <- read.csv("output/surface.area.calc.csv")

# Tissue homogenate volume data
homog_vols <- read_csv("data/homogenate_vols.csv") 

# Coral sample metadata
metadata <- read_csv("data/corals_sampled.csv") %>% select(1:3)

# Join homogenate volumes and surface area with sample metadata
metadata <- full_join(metadata, homog_vols) %>%
  full_join(sa)
```

# Calculate cells per square centimeter
```{r}
# Calculate mean counts for each sample
sym_counts <- sym_counts %>%
  select(full_sample_id, Squares.Counted, matches("Count[0-9]")) %>%
  gather("rep", "count", -full_sample_id, -Squares.Counted) %>%
  group_by(full_sample_id, Squares.Counted) %>%
  summarise(mean_count = mean(count, na.rm = TRUE))

# Join mean counts with sample metadata
sym_counts <- full_join(sym_counts, metadata)

sym_counts <-sym_counts %>%
  filter(!Squares.Counted =="NA")

# Normalize counts by homogenat volume and surface area
sym_counts <- sym_counts %>%
  mutate(cells.mL = mean_count * 10000 / Squares.Counted,
         cells = cells.mL * homog_vol_ml,
         cells.cm2 = cells / surface.area.cm2)
```


# Plot data
```{r}
monthorder <- c("January", "February","March", "April","May",
                "June",  "July", "August", "September", 
                "October","November")

sym_counts$timepoint <- factor(sym_counts$timepoint,levels=monthorder)
sym_counts$group <- paste0(sym_counts$timepoint, "_", sym_counts$site)

# Plot 
sym <- sym_counts %>%
  ggplot(aes(x = timepoint, y = cells.cm2, group=group, color=site)) +
  geom_boxplot(aes(group=group, color=site))+
  geom_jitter(width = 0.1) + # Plot all points
  scale_color_manual(values=c("#E69F00", "#56B4E9")) +
  #stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1),    # Plot standard error
  #             geom = "errorbar", color = c("black"), width = 0.5) +
  #stat_summary(fun.y = mean, geom = "point", color = "black")+           # Plot mean
  labs(x = "", y = "Symbiont Density (cells/cm2)") +
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

sym

ggsave("output/cell_density.jpg", sym, width=6, height=3)

```

